/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonShape, ButtonType } from "./components/my-button/my-button";
import { horizontalAlign, verticalAlign } from "./components/my-modal/my-modal";
export namespace Components {
    interface MyButton {
        "shape": ButtonShape;
        "type": ButtonType;
    }
    interface MyModal {
        "hAlign": horizontalAlign;
        "hasOverlay": boolean;
        "isVisible": boolean;
        "vAlign": verticalAlign;
    }
}
declare global {
    interface HTMLMyButtonElement extends Components.MyButton, HTMLStencilElement {
    }
    var HTMLMyButtonElement: {
        prototype: HTMLMyButtonElement;
        new (): HTMLMyButtonElement;
    };
    interface HTMLMyModalElement extends Components.MyModal, HTMLStencilElement {
    }
    var HTMLMyModalElement: {
        prototype: HTMLMyModalElement;
        new (): HTMLMyModalElement;
    };
    interface HTMLElementTagNameMap {
        "my-button": HTMLMyButtonElement;
        "my-modal": HTMLMyModalElement;
    }
}
declare namespace LocalJSX {
    interface MyButton {
        "shape"?: ButtonShape;
        "type"?: ButtonType;
    }
    interface MyModal {
        "hAlign"?: horizontalAlign;
        "hasOverlay"?: boolean;
        "isVisible"?: boolean;
        "vAlign"?: verticalAlign;
    }
    interface IntrinsicElements {
        "my-button": MyButton;
        "my-modal": MyModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-button": LocalJSX.MyButton & JSXBase.HTMLAttributes<HTMLMyButtonElement>;
            "my-modal": LocalJSX.MyModal & JSXBase.HTMLAttributes<HTMLMyModalElement>;
        }
    }
}
